language: csharp
solution: ./variousConcept/variousConcept.sln
install:
  - nuget restore ./variousConcept/variousConcept.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./variousConcept/variousConcept.sln
 