language: csharp
mono: none
dotnet: 3.1.201
solution: variousConcept.sln
script:
 - dotnet restore

jobs:
  include:
    - stage: compile
       script: skip    
    - stage: test
       script: skip
    - stage: deploy
       script: skip
     
notifications:
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
 